Revert "IMS: Remove API and constants related to ECT."
This reverts commit da40ef630e655574019c4956851c5f318d2882e8.

* fixes E AndroidRuntime: java.lang.NoSuchMethodError: No static method isCallTransferEnabled(Landroid/content/Context;)Z in class Lorg/codeaurora/ims/utils/QtiImsExtUtils; or its super classes